name: stok_takip_uygulamasi
description: "Temel özelliklere sahip stok takip uygulaması."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # Barcode scanning
  mobile_scanner: ^5.2.3
  
  # State management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^16.2.2
  
  # Form validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0
  
  # Environment variables
  flutter_dotenv: ^6.0.0
  
  # Local storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
